Uni\AdminBundle\Entity\Publication:
    type: entity
    table: Publication
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        publication_title:
            type: string
            length: '300'
        publication_content:
            type: text
            nullable: true
        publication_rank:
            type: integer
        publication_active:
            type: boolean
            options:
                default: true
        publication_photo_path:
            type: string
            length: '300'
            nullable: true
        publication_photo_file:
            type: string
            length: '300'
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }
